run:
  timeout: 10m
linters:
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - copyloopvar
  - decorder
  - depguard
  - dogsled
  - durationcheck
  - errcheck
  - exhaustive
  - forbidigo
  - forcetypeassert
  - gci
  - goconst
  - gocritic
  - godot
  - gofmt
  - gofumpt
  - mnd
  - gosec
  - gosimple
  - govet
  - grouper
  - importas
  - ineffassign
  - lll
  - misspell
  - nakedret
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - prealloc
  - predeclared
  - promlinter
  - revive
  - rowserrcheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - wastedassign
  - whitespace
  - tenv
issues:
  exclude-rules:
  - linters:
      - gosec
    text: "integer overflow conversion"
linters-settings:
  goconst:
    min-occurrences: 10
  depguard:
    rules:
      Main:
        list-mode: lax
        allow:
          - $all
  exhaustive:
    # Presence of "default" case in switch statements satisfies exhaustiveness
    default-signifies-exhaustive: true
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true
